### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by codlin** [youfou/wxpy#106]
>>> import ssl
>>> from wxpy import *
鈻>>> bot = Bot()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/itchat/utils.py", line 124, in test_connect
    r = requests.get(config.BASE_URL)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)

You can't get access to internet or wechat domain, so exit.

**Comment by codlin** [comment]
https://github.com/littlecodersh/ItChat/issues/386#issuecomment-307317306
