### ISSUE TITLE
TypeError: 'DataFrame' objects are mutable, thus they cannot be hashed

### ISSUE THREAD

**Issue by yanghui1228** [youfou/wxpy#11]
报错哎，请问怎么解决？

代码：
    my_friend = bot.friends().search('Yang Hui')[0]
    print(my_friend)
    my_friend.send('Hello WeChat!')
=====================
log：
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
TERM environment variable not set.
Login successfully as Yang Hui
<Friend: Yang Hui>
Traceback (most recent call last):
  File "/Users/yanghui/PycharmProjects/quantest/my_strategy/复盘/notices.py", line 23, in <module>
    if key_word in notices.title:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/generic.py", line 871, in __contains__
    return key in self._info_axis
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/indexes/base.py", line 1393, in __contains__
    hash(key)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/generic.py", line 831, in __hash__
    ' hashed'.format(self.__class__.__name__))
TypeError: 'DataFrame' objects are mutable, thus they cannot be hashed

Process finished with exit code 1

**Comment by youfou** [comment]
从traceback看到
```
.../notices.py", line 23, in 
if key_word in notices.title:...
```

出错的位置并非上面的 wxpy 代码，是之后运行的代码出问题了吧？

**Comment by yanghui1228** [comment]
回复好快啊，谢谢！不好意思是我自己搞错了

yang.hui@icloud.com

On 20 Mar 2017, at 10:03 PM, Youfou <notifications@github.com> wrote:

从traceback看到

.../notices.py", line 23, in 
if key_word in notices.title:...
出错的位置并非上面的 wxpy 代码，是之后运行的代码出问题了吧？
