### ISSUE TITLE
机器人运行一段时间后停止运行，报如下错误

### ISSUE THREAD

**Issue by leemon9527** [youfou/wxpy#110]
我使用的是wechat_sender。
下面是我报错的代码

> ERROR:tornado.application:Exception in callback <functools.partial object at 0x7fc857b51838>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 1026, in _run
    return self.callback()
  File "/usr/local/lib/python2.7/site-packages/wechat_sender/listener.py", line 238, in check_bot
    glb.wxbot.send_msg(message)
  File "/usr/local/lib/python2.7/site-packages/wechat_sender/objects.py", line 57, in send_msg
    current_receiver.send_msg(msg)
  File "/usr/local/lib/python2.7/site-packages/wxpy/api/chats/chat.py", line 54, in wrapped
    ret = do_send()
  File "/usr/local/lib/python2.7/site-packages/wxpy/utils/misc.py", line 71, in wrapped
    smart_map(check_response_body, ret)
  File "/usr/local/lib/python2.7/site-packages/wxpy/utils/misc.py", line 205, in smart_map
    return func(i, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/wxpy/utils/misc.py", line 52, in check_response_body
    raise ResponseError(err_code=err_code, err_msg=err_msg)
ResponseError: err_code: 3; err_msg:

错误类型为3，我翻看了下itchat和wxpy中对于这种错误类型的定义只有 

> TRANSLATION = {
    'Chinese': {
        -1000: u'返回值不带BaseResponse',
        -1001: u'无法找到对应的成员',
        -1002: u'文件位置错误',
        -1003: u'服务器拒绝连接',
        -1004: u'服务器返回异常值',
        -1005: u'参数错误',
        0: u'请求成功',
    },
}

可以帮忙看下是什么原因导致的意外中止吗

**Comment by larry19840909** [comment]
看栈像是网络问题，跟wxpy貌似没关系。

**Comment by hainan89** [comment]
我也遇到了这个问题

运行一段时间后，报err_code : 3的错误，
然后就是网络连接超时，最后导致wxpy不工作了

不知道你有找到解决方法吗？

看报错堆栈，和ichat 有关，也有可能是 微信的 web服务端做了一些工作，
强制web连接在一定时间后就终端必须重新连接了。

求解决方案？

能不能试一试 过一段时间，自动退出，自动重新登录的？

**Comment by thewenzhi** [comment]
@hainan89  我也是这样大概运行一天就出现这个问题,请问你现在解决没有?

**Comment by leemon9527** [comment]
@thewenzhi 换一个好一点的双开应用就好了

**Comment by thewenzhi** [comment]
@leemon9527 什么好一点的双开应用 能具体点吗？我就单单用wxpy 每个小时固定发一条消息给好友而已都不行

**Comment by xuefer** [comment]
手机端长时间不在线就会这样。。。一旦在线了又可以了（只要没提示LOGOUT)

**Comment by leemon9527** [comment]
@thewenzhi 我后面换了小米的手机，系统自带应用双开就好了，你可以搜索下小米用的双开是哪家的

**Comment by leemon9527** [comment]
@xuefer 双开应用需要保持后台运行。

**Comment by thewenzhi** [comment]
@leemon9527  为什么要双开应用？  就一个微信号登录 另开一个应用做什么
