### ISSUE TITLE
消息发了就报错 啥情况压 高手

### ISSUE THREAD

**Issue by ifour333** [youfou/wxpy#141]
# 导入模块
from wxpy import *
# 初始化机器人，扫码登陆
bot = Bot()
my_friend = bot.friends()
my_friend[0].send("gdfdfgdf")
for f in my_friend:
     print(f)

Login successfully as Xixi.X
Traceback (most recent call last):
  File "L:/python2/go.py", line 6, in <module>
    my_friend[0].send("gdfdfgdf")
  File "D:\Program Files (x86)\Python36-32\lib\site-packages\wxpy\api\chats\chat.py", line 163, in send
    return self.send_msg(msg=content)
  File "D:\Program Files (x86)\Python36-32\lib\site-packages\wxpy\api\chats\chat.py", line 54, in wrapped
    ret = do_send()
  File "D:\Program Files (x86)\Python36-32\lib\site-packages\wxpy\utils\misc.py", line 72, in wrapped
    smart_map(check_response_body, ret)
  File "D:\Program Files (x86)\Python36-32\lib\site-packages\wxpy\utils\misc.py", line 207, in smart_map
    return func(i, *args, **kwargs)
  File "D:\Program Files (x86)\Python36-32\lib\site-packages\wxpy\utils\misc.py", line 53, in check_response_body
    raise ResponseError(err_code=err_code, err_msg=err_msg)
wxpy.exceptions.ResponseError: err_code: 1204; err_msg:

**Comment by ifour333** [comment]
解决了已经

**Comment by dyhfox** [comment]
大神我也碰到了相同的问题，请问你是怎么解决的？

**Comment by disadone** [comment]
咋解决的也不讲讲

**Comment by feelingu1314** [comment]
> 1204: 通常因为操作对象不为好友关系。例如尝试向一位不为好友的群员发送消息时，会引起这个错误。
如果还有问题可以将代码放上来看一下 @dyhfox
