### ISSUE TITLE
浏览器可以打开wxweb，使用程序提示无法联系到微信服务器

### ISSUE THREAD

**Issue by sharkyc** [youfou/wxpy#173]
错误提示：
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Python34\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python34\lib\ssl.py", line 365, in wrap_socket
    _context=self)
  File "C:\Python34\lib\ssl.py", line 583, in __init__
    self.do_handshake()
  File "C:\Python34\lib\ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python34\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\itchat\utils.py", line 124, in test_connect
    r = requests.get(config.BASE_URL)
  File "C:\Python34\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python34\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))

You can't get access to internet or wechat domain, so exit.

**Comment by mapleflow** [comment]
SSL: CERTIFICATE_VERIFY_FAILED

**Comment by linchuanXu** [comment]
You can't get access to internet or wechat domain, so exit.
同样的问题

**Comment by sharkyc** [comment]
在上面已经适用ssl._create_default_https_context = ssl._create_unverified_context关闭了SSL证书验证而且本地电脑运行就正常 放在服务器上面运行就这样提示





------------------ 原始邮件 ------------------
发件人: "mapleflow";<notifications@github.com>;
发送时间: 2017年8月31日(星期四) 上午8:45
收件人: "youfou/wxpy"<wxpy@noreply.github.com>; 
抄送: "Sharkyc"<sharkyc@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youfou/wxpy] 浏览器可以打开wxweb，使用程序提示无法联系到微信服务器 (#173)




SSL: CERTIFICATE_VERIFY_FAILED

**Comment by mapleflow** [comment]
服务器像阿里云，操作系统CentOS等之类的，安全证书会有此类问题，要么就是 requests urllib3 的版本问题。检查下防火墙的设置。

requests 和 urllib3 的版本问题，我也是经常遇到下面的错误，没有想到什么解决办法。

```
Connection aborted.', gaierror(-2, 'Name or service not known')
HTTPSConnectionPool(host='wx2.qq.com', port=443): Read timed out. (read timeout=30)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))
```

https://github.com/requests/requests/issues/2811
