### ISSUE TITLE
每次只要微信号使用过一天了，第二天就会抛出FileNotFoundError这个异常，我的环境可能是2.7的所以是这样，但是怎么才能不抛这个异常那？（乌班图主机）

### ISSUE THREAD

**Issue by zgmd** [youfou/wxpy#175]
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Traceback (most recent call last):
  File "wx.py", line 12, in <module>
    bot = Bot(console_qr=-2)
  File "/usr/local/lib/python2.7/dist-packages/wxpy/api/bot.py", line 88, in __init__
    except FileNotFoundError as e:
NameError: global name 'FileNotFoundError' is not defined

**Comment by mapleflow** [comment]
![repository-search-your-question](https://user-images.githubusercontent.com/24956551/29954027-6460e2d2-8e9a-11e7-889e-4d694e31dbdc.png)

自己先找找

**Comment by onestone1879** [comment]
同样的问题，换个微信也不行，把程序从Linux移到Windows上用新微信能登录，但收不到群消息。

**Comment by onestone1879** [comment]
`sudo pip install --upgrade itchat -i "https://pypi.doubanio.com/simple/"`
在国外或者开VPN的话后半段可以不要
非Linux的话sudo可以不要

补充一下问题的说明：
当扫描完二维码后，出现“NameError: global name 'FileNotFoundError' is not defined”错误，但是前一天同样的代码还没有问题，怀疑被封，换微信号，仍然不好用，代码移到Windows后能登陆，但功能有限制。
追踪这个错误后，发现是抛出了未定义的异常，将该处代码的try…catch…块注释掉后，重新执行抛出如下错误：
![image](https://user-images.githubusercontent.com/3798193/29977233-428a1b80-8f6f-11e7-9a2f-617ffffe8b02.png)
红线标注部分显示在解析requests.Response的内容时出错，对 r 进行跟踪。结果如下：
![image](https://user-images.githubusercontent.com/3798193/29977289-7ce7dbc8-8f6f-11e7-9b04-12bc36e3b460.png)
response代码为200但返回内容为空，所以才出现了问题，但为何为空，没有找到原因。
期间查看了Github上littlecodersh/ItChat的源码，发现与本地安装的有所不同，尝试更新itchat后，就能够正常登陆了。
所以，解决了问题，但没找到原因。

**Comment by zgmd** [comment]
wxpy 不用使用那个分支的吗？

**Comment by zgmd** [comment]
更新了itchat ，还是不行

**Comment by onestone1879** [comment]
就是被封号了

**Comment by ShanChuangxin** [comment]
还没有到微信扫码的地步，直接bot = Bot()时就报错了
