### ISSUE TITLE
socket.timeout: The read operation timed out

### ISSUE THREAD

**Issue by mapleflow** [youfou/wxpy#179]
env

```
python 3.4.4
ubuntu 16.04
requests (2.18.4)
urllib3 (1.22)
new-core 直接使用的源码
```
desc: 登录一段时间后自动掉线，多个账号有同样的问题。

log:

```
Exception in thread data_sync_loop:
Traceback (most recent call last):
  File "/webapps/wechat/env/lib/python3.4/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/webapps/wechat/env/lib/python3.4/site-packages/urllib3/connectionpool.py", line 383, in _make_request                                                   
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 769, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 641, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/webapps/wechat/env/lib/python3.4/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/webapps/wechat/env/lib/python3.4/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/webapps/wechat/env/lib/python3.4/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/webapps/wechat/env/lib/python3.4/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/webapps/wechat/env/lib/python3.4/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/webapps/wechat/env/lib/python3.4/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/webapps/wechat/env/lib/python3.4/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)                                                                       
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='wx2.qq.com', port=443): Read timed out. (read timeout=30)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/webapps/wechat/wechat/wxpy/api/core.py", line 498, in data_sync_loop
    self.sync()
  File "/webapps/wechat/wechat/wxpy/api/core.py", line 559, in sync
    timeout=(10, 30),
  File "/webapps/wechat/wechat.py", line 65, in post_hook
    resp = self.session.post(url, **kwargs)
  File "/webapps/wechat/env/lib/python3.4/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/webapps/wechat/env/lib/python3.4/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/webapps/wechat/env/lib/python3.4/site-packages/requests/sessions.py", line 618, in send                                                                 
    r = adapter.send(request, **kwargs)
  File "/webapps/wechat/env/lib/python3.4/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='wx2.qq.com', port=443): Read timed out. (read timeout=30)

```

**Comment by lichongsw** [comment]
同问，二十几个小时就会掉线。

**Comment by mapleflow** [comment]
一个手机100群，400好友，报错但是压根没掉线，在线一个多月（只收消息不发消息）

另两个手机（50群、600好友，10群、100好友），报错几个小时后掉线。（一天偶尔发几条消息）

暂时无解。@lichongsw
