### ISSUE TITLE
登录成功后获取不到bot.self.puid是为什么

### ISSUE THREAD

**Issue by chen123123qwe** [youfou/wxpy#180]
2017-09-04 14:12:35 [DEBUG] get qrcode callback uuid:4eisqni2vg== status=201
2017-09-04 14:12:35 [DEBUG] 用户已扫码成功
Please press confirm on your phone.
2017-09-04 14:12:36 [DEBUG] get qrcode callback uuid:4eisqni2vg== status=200
2017-09-04 14:12:36 [DEBUG] 登录成功
Loading the contact, this may take a little while.
Login successfully as
2017-09-04 14:12:36 [DEBUG] {None: <Bot: None>}
Exception in thread robotLogin:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "robot.py", line 225, in robotLogin
    debug("================bot get puid:" + bot.self.puid)
TypeError: must be str, not NoneType

**Comment by chen123123qwe** [comment]
自从掉线一次之后，就这样了。正常状态下不会拿不到

**Comment by chen123123qwe** [comment]
把缓存文件删除之后才可以成功登录，这是什么情况呢？
