### ISSUE TITLE
扫码后不能成功登陆

### ISSUE THREAD

**Issue by NxDon** [youfou/wxpy#186]
之前通过机器人成功登陆过，但是不知道为什么早上就不行了
报错信息如下 
```
Loading the contact, this may take a little while.
INFO:itchat:Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "robot.py", line 13, in <module>
    bot = Bot(cache_path=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/itchat/components/register.py", line 30, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/itchat/components/login.py", line 66, in login
    self.show_mobile_login()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/itchat/components/login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'

```
请问这是什么原因导致的，是微信那边端口变了吗？

**Comment by heqiuzhi** [comment]
我也是诶，昨天都可以，今天不行了！！！

**Comment by mapleflow** [comment]
https://github.com/search?l=Python&q=pass_ticket&type=Issues&utf8=%E2%9C%93

**Comment by heqiuzhi** [comment]
被封号了一般多久可以解封啊？

**Comment by NxDon** [comment]
得出结论，被封了。。。

**Comment by mapleflow** [comment]
@heqiuzhi 封号一般不会解封了,要么重新删除注册(不保证成功).
