### ISSUE TITLE
扫码登录不上去

### ISSUE THREAD

**Issue by GreenGitHuber** [youfou/wxpy#193]
启动以后，扫二维码，就报错：
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from weixin_robot import bot
  File "/Users/uband/git/uband-robot-2/weixin_robot/__init__.py", line 44, in <module>
    logout_callback=handler.logout_event_handler
  File "/Users/uband/git/bot-env/lib/python3.6/site-packages/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/Users/uband/git/bot-env/lib/python3.6/site-packages/itchat/components/register.py", line 30, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/Users/uband/git/bot-env/lib/python3.6/site-packages/itchat/components/login.py", line 66, in login
    self.show_mobile_login()
  File "/Users/uband/git/bot-env/lib/python3.6/site-packages/itchat/components/login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'

**Comment by mapleflow** [comment]
https://github.com/search?l=Python&q=pass_ticket&type=Issues&utf8=%E2%9C%93
