### ISSUE TITLE
登陆时报global name 'FileNotFoundError' is not defined错误

### ISSUE THREAD

**Issue by YuzhouZhang** [youfou/wxpy#195]
Traceback (most recent call last):
  File "/home/zhangyuzhou/PycharmProjects/AlfrescoToWeixin/AlfrescoToWeixin.py", line 11, in <module>
    bot = Bot()
  File "/usr/lib/python2.7/site-packages/wxpy/api/bot.py", line 88, in __init__
    except FileNotFoundError as e:
NameError: global name 'FileNotFoundError' is not defined

**Comment by mapleflow** [comment]
https://github.com/youfou/wxpy/search?q=FileNotFoundError&type=Issues&utf8=%E2%9C%93
