### ISSUE TITLE
TypeError: sync_message_in_groups() missing 2 required positional arguments: 'ms g' and 'groups'

### ISSUE THREAD

**Issue by xgocn** [youfou/wxpy#196]
Login successfully as 落潮拾贝
Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    'Topic :: Utilities',
  File "d:\Anaconda3\envs\test_py3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "d:\Anaconda3\envs\test_py3\lib\distutils\dist.py", line 955, in run_comm
ands
    self.run_command(cmd)
  File "d:\Anaconda3\envs\test_py3\lib\distutils\dist.py", line 974, in run_comm
and
    cmd_obj.run()
  File "d:\Anaconda3\envs\test_py3\lib\site-packages\setuptools\command\test.py"
, line 215, in run
    self.run_tests()
  File "d:\Anaconda3\envs\test_py3\lib\site-packages\setuptools\command\test.py"
, line 238, in run_tests
    **exit_kwarg
  File "d:\Anaconda3\envs\test_py3\lib\unittest\main.py", line 94, in __init__
    self.parseArgs(argv)
  File "d:\Anaconda3\envs\test_py3\lib\unittest\main.py", line 124, in parseArgs

    self._do_discovery([])
  File "d:\Anaconda3\envs\test_py3\lib\unittest\main.py", line 229, in _do_disco
very
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "d:\Anaconda3\envs\test_py3\lib\unittest\loader.py", line 341, in discove
r
    tests = list(self._find_tests(start_dir, pattern))
  File "d:\Anaconda3\envs\test_py3\lib\unittest\loader.py", line 398, in _find_t
ests
    full_path, pattern, namespace)
  File "d:\Anaconda3\envs\test_py3\lib\unittest\loader.py", line 475, in _find_t
est_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "d:\Anaconda3\envs\test_py3\lib\site-packages\setuptools\command\test.py"
, line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "d:\Anaconda3\envs\test_py3\lib\unittest\loader.py", line 190, in loadTes
tsFromName
    return self.loadTestsFromModule(obj)
  File "d:\Anaconda3\envs\test_py3\lib\site-packages\setuptools\command\test.py"
, line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "d:\Anaconda3\envs\test_py3\lib\unittest\loader.py", line 204, in loadTes
tsFromName
    test = obj()
TypeError: sync_message_in_groups() missing 2 required positional arguments: 'ms
g' and 'groups'

(test_py3) D:\wxpy-master>

**Comment by xgocn** [comment]
有时又显示为：


Login successfully as 落潮拾贝
Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    'Topic :: Utilities',
  File "d:\Anaconda3\envs\test_py3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "d:\Anaconda3\envs\test_py3\lib\distutils\dist.py", line 955, in run_com
ands
    self.run_command(cmd)
  File "d:\Anaconda3\envs\test_py3\lib\distutils\dist.py", line 974, in run_com
and
    cmd_obj.run()
  File "d:\Anaconda3\envs\test_py3\lib\site-packages\setuptools\command\test.py
, line 215, in run
    self.run_tests()
  File "d:\Anaconda3\envs\test_py3\lib\site-packages\setuptools\command\test.py
, line 238, in run_tests
    **exit_kwarg
  File "d:\Anaconda3\envs\test_py3\lib\unittest\main.py", line 94, in __init__
    self.parseArgs(argv)
  File "d:\Anaconda3\envs\test_py3\lib\unittest\main.py", line 124, in parseArg

    self._do_discovery([])
  File "d:\Anaconda3\envs\test_py3\lib\unittest\main.py", line 229, in _do_disc
very
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "d:\Anaconda3\envs\test_py3\lib\unittest\loader.py", line 341, in discov
r
    tests = list(self._find_tests(start_dir, pattern))
  File "d:\Anaconda3\envs\test_py3\lib\unittest\loader.py", line 398, in _find_
ests
    full_path, pattern, namespace)
  File "d:\Anaconda3\envs\test_py3\lib\unittest\loader.py", line 475, in _find_
est_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "d:\Anaconda3\envs\test_py3\lib\site-packages\setuptools\command\test.py
, line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "d:\Anaconda3\envs\test_py3\lib\unittest\loader.py", line 190, in loadTe
tsFromName
    return self.loadTestsFromModule(obj)
  File "d:\Anaconda3\envs\test_py3\lib\site-packages\setuptools\command\test.py
, line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "d:\Anaconda3\envs\test_py3\lib\unittest\loader.py", line 204, in loadTe
tsFromName
    test = obj()
TypeError: sync_message_in_groups() missing 2 required positional arguments: 'm
g' and 'groups'
Exception in thread _listen:
Traceback (most recent call last):
  File "d:\Anaconda3\envs\test_py3\lib\threading.py", line 916, in _bootstrap_i
ner
    self.run()
  File "d:\Anaconda3\envs\test_py3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "d:\wxpy-master\wxpy\api\bot.py", line 504, in _listen
    msg = Message(self.core.msgList.get(timeout=0.5), self)
  File "d:\wxpy-master\wxpy\api\messages\message.py", line 49, in __init__
    setattr(self, 'reply' + method, getattr(self.chat, 'send' + method))
  File "d:\wxpy-master\wxpy\api\messages\message.py", line 317, in chat
    return self.receiver
  File "d:\wxpy-master\wxpy\api\messages\message.py", line 339, in receiver
    return self._get_chat_by_user_name(self.raw.get('ToUserName'))
  File "d:\wxpy-master\wxpy\api\messages\message.py", line 381, in _get_chat_by
user_name
    _chat = match_in_chats(self.bot.friends())
  File "d:\wxpy-master\wxpy\utils\misc.py", line 87, in wrapped
    func, self, bot
ValueError: bot not found:m
method: <function Bot.friends at 0x036E0270>
self: <Bot: 落潮拾贝>
bot: None
