### ISSUE TITLE
二维码扫描登陆抛异常，无法登录

### ISSUE THREAD

**Issue by zhangjunwei** [youfou/wxpy#198]
Please scan the QR code to log in.
Please press confirm on your phone.
Traceback (most recent call last):
  File "gdg.py", line 20, in <module>
    bot = Bot(cache_path=True, console_qr=-2, qr_path=None, qr_callback=None, login_callback=None, logout_callback=None)
  File "/usr/local/lib/python3.6/site-packages/wxpy/api/bot.py", line 74, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/usr/local/lib/python3.6/site-packages/itchat/components/register.py", line 30, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 48, in login
    status = self.check_login()
  File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 131, in check_login
    process_login_info(self, r.text)
  File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 164, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/usr/local/lib/python3.6/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/local/lib/python3.6/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/local/lib/python3.6/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

**Comment by zhangjunwei** [comment]
用微信官方网页端扫描登录，提示：<error><ret>1203</ret><message>当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过手机客户端或者windows微信登录。</message></error>
看来也是网页端被封了！

**Comment by slyang-git** [comment]
同样遇到这个问题。

**Comment by Memoky** [comment]
>为了你的帐号安全，新注册的微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录 我直接提示这个了

**Comment by wenoptics** [comment]
@zhangjunwei 请问现在如何？大约过了多久解禁呢？
