### ISSUE TITLE
Message are sent out successfully but then raise exeception "KeyError: 'self'"

### ISSUE THREAD

**Issue by slxiao** [youfou/wxpy#20]
Using python3.5, and in Linux ENV.

In [43]: my_wife.send("test")
Out[43]: <ItchatReturnValue: {'MsgID': '8287475435897459665', 'LocalID': '14904491571103', 'BaseResponse': {'RawMsg': '请求成功', 'Ret': 0, 'ErrMsg': '请求成功'}}>

In [44]: Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.5/site-packages/itchat/components/login.py", line 240, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "/home/mint/.local/lib/python3.5/site-packages/itchat/components/messages.py", line 61, in produce_msg
    produce_group_chat(core, m)
  File "/home/mint/.local/lib/python3.5/site-packages/itchat/components/messages.py", line 250, in produce_group_chat
    atFlag = '@' + (chatroom['self']['DisplayName']
KeyError: 'self'

**Comment by youfou** [comment]
这个问题还在定位中，不过似乎并不影响使用…
话说现在仍然存在这个问题吗？
我这里原来也遇到过，不过现在无法重现了……

**Comment by youfou** [comment]
@slxiao itchat 的作者找到了问题，已经更新了版本，请在更新itchat后再试试，看还会不会遇到这个问题

    pip3 install -U itchat
