### ISSUE TITLE
无法send中文

### ISSUE THREAD

**Issue by j704794464** [youfou/wxpy#202]
我尝试在错误信息说的那两个文件前面加上：
#!/usr/bin/python
# -*- coding: utf-8 -*-
但是还是没有解决
以下是错误信息：
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Python27\lib\site-packages\wxpy\api\chats\chat.py", line 154, in send
    content = str('' if content is None else content)
  File "C:\Python27\lib\site-packages\future\types\newstr.py", line 105, in __new__
    return super(newstr, cls).__new__(cls, value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 0: ordinal not in range(128)

**Comment by mapleflow** [comment]
py2 破事多。

**Comment by j704794464** [comment]
好吧，那我用3好了，谢谢大佬回答

**Comment by WellerQu** [comment]
```python
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

new_friend = bot.accept_friend(msg.card)
new_friend.send(u'你好, 很高心认识你');
```

以上, 是我程序中的部分代码. 也许能帮到你.

**Comment by xiaods** [comment]
加个u就可以。
