### ISSUE TITLE
name 'Bot' is not defined？

### ISSUE THREAD

**Issue by zuiailiesha** [youfou/wxpy#219]
python版本3.6.2

安装完wxpy后，执行最简单的：
from wxpy import *
bot = Bot()
报错。

Traceback (most recent call last):
  File "D:\Python\wxpy\wxpy.py", line 1, in <module>
    from wxpy import *
  File "D:\Python\wxpy\wxpy.py", line 3, in <module>
    bot = Bot()
NameError: name 'Bot' is not defined

请问是什么情况？谢谢！

**Comment by mapleflow** [comment]
文件不要和类库（模块）同名。

**Comment by zuiailiesha** [comment]
mapleflow正解，惭愧犯了这么低级的错误。。

**Comment by xgdgsc** [comment]
这个可以close

**Comment by Windsmild** [comment]
赞 解决了
