### ISSUE TITLE
视频发送不成功

### ISSUE THREAD

**Issue by hankzhaoo** [youfou/wxpy#221]
图片可以正常发送，但视频无法发送成功
<img width="729" alt="2017-10-31 2 44 14" src="https://user-images.githubusercontent.com/31267637/32210687-10c5f8a2-bddd-11e7-8c42-847e121f6586.png">

**Comment by modun** [comment]
能发送文字，但不能发送图片

Traceback (most recent call last):
  File "wxpy_self.py", line 6, in <module>
    bot.file_helper.send_image('test.jpg')
  File "/usr/local/lib/python2.7/dist-packages/wxpy/api/chats/chat.py", line 54, in wrapped
    ret = do_send()
  File "/usr/local/lib/python2.7/dist-packages/wxpy/utils/misc.py", line 72, in wrapped
    smart_map(check_response_body, ret)
  File "/usr/local/lib/python2.7/dist-packages/wxpy/utils/misc.py", line 207, in smart_map
    return func(i, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wxpy/utils/misc.py", line 53, in check_response_body
    raise ResponseError(err_code=err_code, err_msg=err_msg)
wxpy.exceptions.ResponseError: err_code: 1; err_msg: 



![image](https://user-images.githubusercontent.com/19634102/33022606-bb01c8c8-ce40-11e7-91b1-cd573ca0499e.png)
![_20171120221842](https://user-images.githubusercontent.com/19634102/33022636-cea2cd0a-ce40-11e7-9d9c-bd82bec99d00.png)

**Comment by gswf-sha** [comment]
same here, send_file或send_video的错误相同：
Traceback (most recent call last):

  File "<ipython-input-13-89e7533f96e4>", line 1, in <module>
    yf.send_video('index.mp4')

  File "/Users/yefeng/anaconda/envs/ds/lib/python3.5/site-packages/wxpy/api/chats/chat.py", line 54, in wrapped
    ret = do_send()

  File "/Users/yefeng/anaconda/envs/ds/lib/python3.5/site-packages/wxpy/utils/misc.py", line 71, in wrapped
    smart_map(check_response_body, ret)

  File "/Users/yefeng/anaconda/envs/ds/lib/python3.5/site-packages/wxpy/utils/misc.py", line 205, in smart_map
    return func(i, *args, **kwargs)

  File "/Users/yefeng/anaconda/envs/ds/lib/python3.5/site-packages/wxpy/utils/misc.py", line 52, in check_response_body
    raise ResponseError(err_code=err_code, err_msg=err_msg)

ResponseError: err_code: 1; err_msg: 

--------------------------------------

Traceback (most recent call last):

  File "<ipython-input-14-9e5f2657c7e8>", line 1, in <module>
    yf.send_file('index.mp4')

  File "/Users/yefeng/anaconda/envs/ds/lib/python3.5/site-packages/wxpy/api/chats/chat.py", line 54, in wrapped
    ret = do_send()

  File "/Users/yefeng/anaconda/envs/ds/lib/python3.5/site-packages/wxpy/utils/misc.py", line 71, in wrapped
    smart_map(check_response_body, ret)

  File "/Users/yefeng/anaconda/envs/ds/lib/python3.5/site-packages/wxpy/utils/misc.py", line 205, in smart_map
    return func(i, *args, **kwargs)

  File "/Users/yefeng/anaconda/envs/ds/lib/python3.5/site-packages/wxpy/utils/misc.py", line 52, in check_response_body
    raise ResponseError(err_code=err_code, err_msg=err_msg)

ResponseError: err_code: 1; err_msg:

**Comment by dan6886** [comment]
更新 itchat 的版本到：itchat 1.3.10
pip install --upgrade itchat
