### ISSUE TITLE
现在好像不可以通过add_all添加群成员了？

### ISSUE THREAD

**Issue by wxrapha** [youfou/wxpy#241]

**Comment by wxrapha** [comment]
c = bot.chats().search(puid=puid)
print type(c)
c.add_all()

Traceback (most recent call last):
  File "/Users/xiehao/PycharmProjects/untitled6/util/glo1.py", line 36, in <module>
    c.add_all()
  File "/Users/xiehao/weixin/lib/python2.7/site-packages/wxpy/api/chats/chats.py", line 153, in add_all
    ret = adding.add(verify_content=verify_content)
AttributeError: 'Group' object has no attribute 'add'
<class 'wxpy.api.chats.chats.Chats'>

**Comment by wxrapha** [comment]
print(e.err_code, e.err_msg)
(-1, u'')

**Comment by wxrapha** [comment]
没有错误也不会发送好友请求

**Comment by wxrapha** [comment]
多次测试发现会有添加记录，但是不会向好友发送请求， 而且用is_friend检测会出现没有发送好友请求的群聊对象True的情况

**Comment by mapleflow** [comment]
微信有申请和接受好友的限制数量，至于wxpy的检测可能并不准确。

**Comment by yeyong123** [comment]
我也遇到了你这样的问题, 后来你解决了吗?

```
<ItchatReturnValue: {'BaseResponse': {'Ret': 0, 'ErrMsg': '请求成功', 'RawMsg': '请求成功'}}>
```
返回结果好像是成功的
但是没有发送请求
