### ISSUE TITLE
扫描二维码登录wxpy报错:

### ISSUE THREAD

**Issue by Beeta** [youfou/wxpy#242]
日志: 
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/usr/lib/python3.4/site-packages/itchat/components/register.py", line 35, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/lib/python3.4/site-packages/itchat/components/login.py", line 66, in login
    self.show_mobile_login()
  File "/usr/lib/python3.4/site-packages/itchat/components/login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'

**Comment by knight0zh** [comment]
同样的问题

**Comment by ZHLHZHU** [comment]
+1(￣▽￣")
应该是帐号问题，直接用账号登录微信网页版会弹出提示：

> 为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com

**Comment by knight0zh** [comment]
那就是用不了

**Comment by ppppfly** [comment]
用不了了，
```python
Traceback (most recent call last):
  File "/Users/pang/WorkSpace/mbrs/wechat_rebot/auto_record/auto_record.py", line 6, in <module>
    bot = Bot()
  File "/Users/pang/WorkSpace/mbrs/wechat_rebot/venv/lib/python3.6/site-packages/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/Users/pang/WorkSpace/mbrs/wechat_rebot/venv/lib/python3.6/site-packages/itchat/components/register.py", line 35, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/Users/pang/WorkSpace/mbrs/wechat_rebot/venv/lib/python3.6/site-packages/itchat/components/login.py", line 66, in login
    self.show_mobile_login()
  File "/Users/pang/WorkSpace/mbrs/wechat_rebot/venv/lib/python3.6/site-packages/itchat/components/login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'
```

微信网页版，掐得死死地，新的账号，扫码一次我们的生产的二维码，马上被封。
估计是对原来的登陆二维码做了标记，成了一个 `陷阱`。

**Comment by babopo** [comment]
同样的问题。。

**Comment by jackPanyj** [comment]
有解决方案没，遇到了同样的问题。
![image](https://user-images.githubusercontent.com/12585605/34762575-2ee7b978-f623-11e7-83b3-9a290c85faa5.png)

**Comment by mapleflow** [comment]
可以PC端挂机N天或者等待自然解封，新号码的话最好来点人的操作。

**Comment by wenoptics** [comment]
调试大概到第4天出现这个问题：去网页扫描提示

> 当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过Windows微信、Mac微信或者手机客户端微信登录。

我的traceback
```
Traceback (most recent call last):
  File "C:\Users\op\Anaconda3\envs\cr-bot\lib\site-packages\wxpy\api\bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "C:\Users\op\Anaconda3\envs\cr-bot\lib\site-packages\itchat\components\register.py", line 30, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "C:\Users\op\Anaconda3\envs\cr-bot\lib\site-packages\itchat\components\login.py", line 48, in login
    status = self.check_login()
  File "C:\Users\op\Anaconda3\envs\cr-bot\lib\site-packages\itchat\components\login.py", line 131, in check_login
    process_login_info(self, r.text)
  File "C:\Users\op\Anaconda3\envs\cr-bot\lib\site-packages\itchat\components\login.py", line 164, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "C:\Users\op\Anaconda3\envs\cr-bot\lib\xml\dom\minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "C:\Users\op\Anaconda3\envs\cr-bot\lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "C:\Users\op\Anaconda3\envs\cr-bot\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

请问大家多久解禁？
@Beeta

**Comment by Anynices** [comment]
微信网页版登录正常，仍然出现这个错误

**Comment by davidkorea** [comment]
我也是，第一次扫码成功了，之后再用就报错，然而微信网页版登录正常。。。

**Comment by cqychen** [comment]
我要是微信网页版本，正常登录，但是运行程序就是报错。

**Comment by xxxifan** [comment]
我好多年的老号也登录不了网页微信
