### ISSUE TITLE
大神 现在不能发送图片消息了吗？

### ISSUE THREAD

**Issue by feixiangingk** [youfou/wxpy#247]
Python2.7 win10  报错如下
F:\ZTworkspace\build_up\test_wxpy\111.jpg
Traceback (most recent call last):
  File "F:/ZTworkspace/build_up/test_wxpy/test_wx.py", line 66, in <module>
    send_file_helper()
  File "F:/ZTworkspace/build_up/test_wxpy/test_wx.py", line 24, in send_file_helper
    bot.file_helper.send_image(path)
  File "F:\Python2.7\lib\site-packages\wxpy\api\chats\chat.py", line 54, in wrapped
    ret = do_send()
  File "F:\Python2.7\lib\site-packages\wxpy\utils\misc.py", line 72, in wrapped
    smart_map(check_response_body, ret)
  File "F:\Python2.7\lib\site-packages\wxpy\utils\misc.py", line 207, in smart_map
    return func(i, *args, **kwargs)
  File "F:\Python2.7\lib\site-packages\wxpy\utils\misc.py", line 53, in check_response_body
    raise ResponseError(err_code=err_code, err_msg=err_msg)
wxpy.exceptions.ResponseError: err_code: 1; err_msg:

**Comment by dota2heqiuzhi** [comment]
+1
