### ISSUE TITLE
关于发送图片的问题

### ISSUE THREAD

**Issue by ghost** [youfou/wxpy#262]
首先我使用**git bash**发图片,成功
然后我再用**py**发就会报错,代码如下
希望问题可以解决,谢谢!
```
>>> my_friend.send_image('TIM20180213153646.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\27410\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wxpy\api\chats\chat.py", line 54, in wrapped
    ret = do_send()
  File "C:\Users\27410\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wxpy\utils\misc.py", line 72, in wrapped
    smart_map(check_response_body, ret)
  File "C:\Users\27410\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wxpy\utils\misc.py", line 207, in smart_map
    return func(i, *args, **kwargs)
  File "C:\Users\27410\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wxpy\utils\misc.py", line 53, in check_response_body
    raise ResponseError(err_code=err_code, err_msg=err_msg)
wxpy.exceptions.ResponseError: err_code: -1002; err_msg: 文件位置错误
```

**Comment by dota2heqiuzhi** [comment]
+1

**Comment by lanson647** [comment]
+1 昨天开始一直报错，前天还是好的...同样的代码
