### ISSUE TITLE
登录失败报错，网页版可正常登录

### ISSUE THREAD

**Issue by Anynices** [youfou/wxpy#275]
- 之前一直正常使用，定期重启
 - 扫码之后，等待时间很长
 - 之前出现过一次，手机上清理了缓存及一批好友之后正常
## Log
```
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    bot = Bot()
  File "/usr/local/lib/python3.5/site-packages/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/usr/local/lib/python3.5/site-packages/itchat/components/register.py", line 35, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python3.5/site-packages/itchat/components/login.py", line 67, in login
    self.get_contact(True)
  File "/usr/local/lib/python3.5/site-packages/itchat/components/contact.py", line 284, in get_contact
    seq, batchMemberList = _get_contact(seq)
  File "/usr/local/lib/python3.5/site-packages/itchat/components/contact.py", line 280, in _get_contact
    j = json.loads(r.content.decode('utf-8', 'replace'))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by secreter** [comment]
me too

**Comment by congjunwei** [comment]
me too

**Comment by qizisheng** [comment]
求问这个如何解决？me too

**Comment by JoeyHou** [comment]
Me too! 求解决

**Comment by JoeyHou** [comment]
楼上你们这个问题都解决了吗？

**Comment by riverscn** [comment]
me too

**Comment by ShakeM** [comment]
同样的问题

**Comment by JoeyHou** [comment]
我今天尝试了一下，清理掉了朋友列表中被单方面删除的好友（对方删除了我但是我没有删除对方，ta还留在朋友列表里面，但是发消息会失败、朋友圈也看不见），就可以登陆了，可能可以试一试

**Comment by riverscn** [comment]
@JoeyHou 怎么清理的？

**Comment by JoeyHou** [comment]
@riverscn 我就是一个个看的，单删的会看不到ta的朋友圈。不过有些朋友圈屏蔽了我的也会看不到ta的朋友圈，就得发个消息确认了一下，如果消息还发得出去就不用删。

**Comment by ShakeM** [comment]
@JoeyHou @riverscn 
好友少的话，建议拉群测试，不打扰；
好友多的话用Wetool，清理僵尸粉，也是免打扰的，但自己这边会有系统提示，我已经在清理了。

**Comment by riverscn** [comment]
@ShakeM Wetool 清理会打扰人吗？

**Comment by ShakeM** [comment]
@riverscn 看介绍是免打扰，但本地会收到一条添加好友的消息。

目前已经测试了160多好友，没有好友回复，故推测应该确实是免打扰的。

**Comment by ShakeM** [comment]
经测试，成功解决。该问题应该是僵尸好友过多导致。
2500好友，跑了删除僵尸700个后，成功登陆。
