### ISSUE TITLE
登录失败,报错KeyError: 'pass_ticket'

### ISSUE THREAD

**Issue by liguobao** [youfou/wxpy#283]
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "wechat_robot.py", line 4, in <module>
    bot = Bot()
  File "/usr/local/lib/python3.6/site-packages/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/usr/local/lib/python3.6/site-packages/itchat/components/register.py", line 35, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 66, in login
    self.show_mobile_login()
  File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'

**Comment by liguobao** [comment]
新号被微信限制的,非代码问题/
