### ISSUE TITLE
监听群消息时会报错

### ISSUE THREAD

**Issue by yanweitao** [youfou/wxpy#315]
Exception in thread _listen: Traceback (most recent call last):   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner     self.run()   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run     self._target(*self._args, **self._kwargs)   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wxpy/api/bot.py", line 504, in _listen     msg = Message(self.core.msgList.get(timeout=0.5), self)   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wxpy/api/messages/message.py", line 49, in __init__     setattr(self, 'reply' + method, getattr(self.chat, 'send' + method))   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wxpy/api/messages/message.py", line 319, in chat     return self.sender   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wxpy/api/messages/message.py", line 329, in sender     return self._get_chat_by_user_name(self.raw.get('FromUserName'))   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wxpy/api/messages/message.py", line 379, in _get_chat_by_user_name     _chat = match_in_chats(self.bot.groups())   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wxpy/utils/misc.py", line 96, in wrapped     ret = Groups(ret)   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wxpy/api/chats/groups.py", line 35, in __init__     if group.bot.self in group:   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wxpy/api/chats/group.py", line 42, in __contains__     for member in self.members:   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wxpy/api/chats/group.py", line 36, in members     raw_member_list() or raw_member_list(True)   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wxpy/api/chats/group.py", line 30, in raw_member_list     self.update_group()   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wxpy/api/chats/group.py", line 112, in update_group     super(Group, self).__init__(do(), self.bot)   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wxpy/utils/misc.py", line 67, in wrapped     ret = func(*args, **kwargs)   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wxpy/api/chats/group.py", line 110, in do     return self.bot.core.update_chatroom(self.user_name, members_details)   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/itchat/components/contact.py", line 74, in update_chatroom     update_local_chatrooms(self, chatroomList)   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/itchat/storage.py", line 11, in _contact_change     return fn(core, *args, **kwargs)   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/itchat/components/contact.py", line 154, in update_local_chatrooms     'UserName', oldChatroom['ChatRoomOwner']).get('Uin', 0) AttributeError: 'NoneType' object has no attribute 'get'

**Comment by RicottaZhang** [comment]
我也遇到了这个问题 看来需要加个workaround 例如加个timeout 或者检查到msgList存在了 再监听

**Comment by scarlett5945** [comment]
解决了吗？

**Comment by Maohhh** [comment]
将python3.6\site-packages\itchat\components目录下的contact.py使用root权限打开修改153行为oldChatroom["OwanerUin"] = 0就可以了

**Comment by wogenhaosini** [comment]
> 将python3.6\site-packages\itchat\components目录下的contact.py使用root权限打开修改153行为oldChatroom["OwanerUin"] = 0就可以了

好使，谢谢。
