### ISSUE TITLE
是不是微信好友人数过多就无法登录呢？

### ISSUE THREAD

**Issue by osiku** [youfou/wxpy#322]
微信好友4千多人，bot = Bot()就报错，微信号可以正常登录网页版和PC版。
用其他账号登录就没问题。
现在感觉就是这个账号好友人数比较多，扫完二维码后会卡很久，然后会报下面的错误。
---------------------------
`Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/test.py", line 2, in <module>
    bot = Bot()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\wxpy\api\bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\itchat\components\register.py", line 35, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\itchat\components\login.py", line 67, in login
    self.get_contact(True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\itchat\components\contact.py", line 284, in get_contact
    seq, batchMemberList = _get_contact(seq)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\itchat\components\contact.py", line 280, in _get_contact
    j = json.loads(r.content.decode('utf-8', 'replace'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by izhiliang** [comment]
同样的问题
