### ISSUE TITLE
add_members不可用，报错error_code: 1

### ISSUE THREAD

**Issue by alexmaoshijian** [youfou/wxpy#323]
报错信息如下，请问是不是真的接口被封了？还能解决吗？

```
Traceback (most recent call last):
  File "<pyshell#57>", line 1, in <module>
    group.add_members(friend, use_invitation=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wxpy\utils\misc.py", line 72, in wrapped
    smart_map(check_response_body, ret)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wxpy\utils\misc.py", line 207, in smart_map
    return func(i, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wxpy\utils\misc.py", line 53, in check_response_body
    raise ResponseError(err_code=err_code, err_msg=err_msg)
wxpy.exceptions.ResponseError: err_code: 1; err_msg: 
```

**Comment by yuanyefu** [comment]
你问题解决了吗

**Comment by alexmaoshijian** [comment]
并没有解决，你也碰到了吗？






在 2018-07-22 14:30:43，"yuanyefu" <notifications@github.com> 写道：


你问题解决了吗

**Comment by BasuLee** [comment]
我也碰到了这个问题，不知道什么原因

**Comment by llhe** [comment]
一样的问题，不可用

**Comment by llhe** [comment]
似乎无解 https://github.com/youfou/wxpy/issues/321

**Comment by zzw19880707** [comment]
对方给你们拉黑了

**Comment by chaifly** [comment]
不可用，没报错，有人解决了吗？

**Comment by tetsaicn** [comment]
估计是官方禁止了这个接口，我也遇到

**Comment by dsjakezhou** [comment]
File "E:\wxpy\venv\lib\site-packages\wxpy\api\chats\chat.py", line 54, in wrapped
    ret = do_send()
  File "E:\wxpy\venv\lib\site-packages\wxpy\utils\misc.py", line 72, in wrapped
    smart_map(check_response_body, ret)
  File "E:\wxpy\venv\lib\site-packages\wxpy\utils\misc.py", line 207, in smart_map
    return func(i, *args, **kwargs)
  File "E:\wxpy\venv\lib\site-packages\wxpy\utils\misc.py", line 53, in check_response_body
    raise ResponseError(err_code=err_code, err_msg=err_msg)
wxpy.exceptions.ResponseError: err_code: 1; err_msg: 
LOG OUT!    怎么弄？？？？？

**Comment by wuzhengyi** [comment]
同样不好使……

**Comment by BasuLee** [comment]
接口已下线，望周知

**Comment by zhiweio** [comment]
wechat web 群接口已关闭，目前我只找到了付费的解决方案

**Comment by Cyrus-Jiang** [comment]
> wechat web 群接口已关闭，目前我只找到了付费的解决方案

兄弟请教一下，什么付费的方案？也是微信Web接口吗？

**Comment by zhiweio** [comment]
> > wechat web 群接口已关闭，目前我只找到了付费的解决方案
> 
> 兄弟请教一下，什么付费的方案？也是微信Web接口吗？

https://github.com/Chatie/wechaty
这个库，免费的还是基于 web 接口，没有群功能
付费方案是有 ipad ios... 协议选择，有完整功能

**Comment by Cyrus-Jiang** [comment]
> > > wechat web 群接口已关闭，目前我只找到了付费的解决方案
> > 
> > 
> > 兄弟请教一下，什么付费的方案？也是微信Web接口吗？
> 
> https://github.com/Chatie/wechaty
> 这个库，免费的还是基于 web 接口，没有群功能
> 付费方案是有 ipad ios... 协议选择，有完整功能

多谢了，我去看看
