### ISSUE TITLE
机器人无法登录

### ISSUE THREAD

**Issue by Chen-Han** [youfou/wxpy#330]
以下是错误信息，请问该项目还在维护吗？
```
Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "wechat_bot.py", line 2, in <module>
    bot = Bot()
  File "/usr/local/lib/python3.7/site-packages/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/usr/local/lib/python3.7/site-packages/itchat/components/register.py", line 35, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python3.7/site-packages/itchat/components/login.py", line 66, in login
    self.show_mobile_login()
  File "/usr/local/lib/python3.7/site-packages/itchat/components/login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'
```

**Comment by EthenQ** [comment]
同样的问题

**Comment by Chen-Han** [comment]
@EthenQ 
刚刚解决，这是因为新注册的微信号不允许登录网页微信。
需要等一段时间。
