### ISSUE TITLE
add_friend 和add_all 方法是不是都不能用了？

### ISSUE THREAD

**Issue by fengyewenrou** [youfou/wxpy#333]
Traceback (most recent call last):
  File "C:/Users/acer/PycharmProjects/untitled8/haoyou.py", line 9, in <module>
    female_members.add_all(interval=3, verify_content='hello ')
  File "D:\python\lib\site-packages\wxpy\api\chats\chats.py", line 150, in add_all
    ret = adding.add(verify_content=verify_content)
  File "D:\python\lib\site-packages\wxpy\api\chats\user.py", line 95, in add
    return self.bot.add_friend(user=self, verify_content=verify_content)
  File "D:\python\lib\site-packages\wxpy\utils\misc.py", line 72, in wrapped
    smart_map(check_response_body, ret)
  File "D:\python\lib\site-packages\wxpy\utils\misc.py", line 207, in smart_map
    return func(i, *args, **kwargs)
  File "D:\python\lib\site-packages\wxpy\utils\misc.py", line 53, in check_response_body
    raise ResponseError(err_code=err_code, err_msg=err_msg)
wxpy.exceptions.ResponseError: err_code: 1; err_msg: 
都会报这个错

**Comment by WersonLu** [comment]
你好，请问你解决了么，我用add_friend遇到了同样的报错0.0

**Comment by fengyewenrou** [comment]
> 你好，请问你解决了么，我用add_friend遇到了同样的报错0.0

是微信禁用了web端的加好友接口，以后都不能用了
