### ISSUE TITLE
登陆错误

### ISSUE THREAD

**Issue by guoxinrun** [youfou/wxpy#371]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/itchat/components/login.py", line 231, in maintain_loop
    i = sync_check(self)
  File "/usr/local/lib/python3.4/dist-packages/itchat/components/login.py", line 283, in sync_check
    r = self.s.get(url, params=params, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/wxpy/utils/misc.py", line 351, in customized_request
    return requests.Session.request(session, method, url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 316, in send
    timeout = TimeoutSauce(connect=timeout, read=timeout)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was (10, 30), but it must be an int, float or None.

2019-03-08 11:10:30,018 : INFO : LOG OUT!

**Comment by daiyunchao** [comment]
我的错和你应该是一样的
File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 237, in maintain_loop
    msgList, contactList = self.get_msg()
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 302, in get_msg
    r = self.s.post(url, data=json.dumps(data), headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 497, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wxpy/utils/misc.py", line 351, in customized_request
    return requests.Session.request(session, method, url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 316, in send
    timeout = TimeoutSauce(connect=timeout, read=timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/util.py", line 116, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/lib/python2.7/dist-packages/urllib3/util.py", line 147, in _validate_timeout
    "int or float." % (name, value))
ValueError: Timeout value connect was (10, 20), but it must be an int or float.

**Comment by daiyunchao** [comment]
我的代码很简单:
```python
from wxpy import *
bot = Bot(console_qr=2,cache_path="botoo.pkl")

# 给"文件传输助手"发消息
my_friend = bot.file_helper.send('hello world')

@bot.register()
def print_others(msg):
    print(msg)

embed()
```
