### ISSUE TITLE
现在还能用吗，微信Web版已经不让登录了

### ISSUE THREAD

**Issue by zollty** [youfou/wxpy#405]
RT

**Comment by gwzbenjamin** [comment]
我的也登不了？希望能尽快出一个微信ipad登陆的选项

**Comment by shibing624** [comment]
登录时出错：  
`
File "/Users/xxx/Library/Python/3.6/lib/python/site-packages/itchat/components/login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'
`

**Comment by rangerzhou** [comment]
无法登陆，报错如下：
```
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
Please press confirm on your phone.
Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "./wxpyDemo.py", line 5, in <module>
    bot = Bot()
  File "/usr/local/lib/python3.6/dist-packages/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/usr/local/lib/python3.6/dist-packages/itchat/components/register.py", line 35, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python3.6/dist-packages/itchat/components/login.py", line 66, in login
    self.show_mobile_login()
  File "/usr/local/lib/python3.6/dist-packages/itchat/components/login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'
```

**Comment by sc-1123** [comment]
It's weird that I tried TWO people's wechat accounts and ALL of them can't log in!
Exception:
Traceback (most recent call last):
  File "C:/Users/ealab1/PycharmProjects/ufdse/IDLE.py", line 5, in <module>
    bot = Bot()
  File "C:\Program Files (x86)\Python37\lib\site-packages\wxpy\api\bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "C:\Program Files (x86)\Python37\lib\site-packages\itchat\components\register.py", line 35, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "C:\Program Files (x86)\Python37\lib\site-packages\itchat\components\login.py", line 66, in login
    self.show_mobile_login()
  File "C:\Program Files (x86)\Python37\lib\site-packages\itchat\components\login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'

What's more, please check my program:
https://github.com/wxyes/blob/master/wxyes.py

**Comment by KishinZW** [comment]
It's weird that I tried TWO people's wechat accounts and ALL of them can't log in!
Exception:
Traceback (most recent call last):
File "C:/Users/ealab1/PycharmProjects/ufdse/IDLE.py", line 5, in 
bot = Bot()
File "C:\Program Files (x86)\Python37\lib\site-packages\wxpy\api\bot.py", line 86, in init
loginCallback=login_callback, exitCallback=logout_callback
File "C:\Program Files (x86)\Python37\lib\site-packages\itchat\components\register.py", line 35, in auto_login
loginCallback=loginCallback, exitCallback=exitCallback)
File "C:\Program Files (x86)\Python37\lib\site-packages\itchat\components\login.py", line 66, in login
self.show_mobile_login()
File "C:\Program Files (x86)\Python37\lib\site-packages\itchat\components\login.py", line 212, in show_mobile_login
self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'

What's more, please check my program:
https://github.com/sc-1123/wxyes/blob/master/wxyes.py

**Comment by KishinZW** [comment]
well, I tried my wechat account and the program worked well.

**Comment by xdkaka** [comment]
各位还是不要尝试了，Web端微信已经下架了，新号完全登录不了，老号部分可以登录，不过也在一步步限制

**Comment by shibing624** [comment]
旧号可以使用。新号不行。

**Comment by piiiiiiiiiiiiiii** [comment]
我也想知道

**Comment by piiiiiiiiiiiiiii** [comment]
20190910，登录web wx提示：

<error><ret>1203</ret><message>为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>

**Comment by just-OneKey** [comment]
登录的时候报错：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\DevelopLanguages\Python\Python3.6.8\lib\site-packages\wxpy\api\bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "D:\DevelopLanguages\Python\Python3.6.8\lib\site-packages\itchat\components\register.py", line 35, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "D:\DevelopLanguages\Python\Python3.6.8\lib\site-packages\itchat\components\login.py", line 66, in login
    self.show_mobile_login()
  File "D:\DevelopLanguages\Python\Python3.6.8\lib\site-packages\itchat\components\login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'
各位有解决的办法吗？
还是说这个包已经没法用了

**Comment by Ran-Zherui** [comment]
马化腾我吃柠檬

**Comment by Likenttt** [comment]
这个是微信官方的操作，无解

**Comment by ghost** [comment]
悲报：网页版无法登录，itchat算是白搞了

**Comment by FishMan552** [comment]
mark， 新老号都不行

**Comment by nikenj** [comment]
此项目被微信阉割了。。。
