### ISSUE TITLE
SyntaxError: can use starred expression only as assignment target

### ISSUE THREAD

**Issue by mapleflow** [youfou/wxpy#41]
环境：

    Ubuntu 14.04, Python 3.4
    wxpy 0.3.8，0.3.9 都有这个错误，0.3.6 无错误

代码：

	from wxpy import embed, Bot

    b1 = Bot()
    embed()
    
错误：    
    
    Traceback (most recent call last):
      File "test.py", line 1, in <module>
        from wxpy import embed, Bot
      File "/lib/python3.4/site-packages/wxpy/__init__.py", line 48, in <module>
        from .api.bot import Bot
      File "/lib/python3.4/site-packages/wxpy/api/bot.py", line 12, in <module>
        from ..api.chats import Chat, Chats, Friend, Group, MP, User
      File "/lib/python3.4/site-packages/wxpy/api/chats/__init__.py", line 1, in <module>
        from .chat import Chat
      File "/lib/python3.4/site-packages/wxpy/api/chats/chat.py", line 8, in <module>
        from wxpy.utils import PuidMap, handle_response
      File "/lib/python3.4/site-packages/wxpy/utils/__init__.py", line 5, in <module>
        from .puid_map import PuidMap
      File "/lib/python3.4/site-packages/wxpy/utils/puid_map.py", line 121
        pickle.dump((*self.attr_dicts, self.captions), fp)
                                ^
    SyntaxError: can use starred expression only as assignment target

**Comment by youfou** [comment]
查了下，这个语法是在 Python 3.5 后才开始使用的，因此在老版本中报语法错误。
http://stackoverflow.com/questions/34766677/python-splat-unpack-operator-in-python-cannot-be-used-in-an-expression

感谢反馈！

我修改了代码，请试试安装开发分支上的版本，应该不会报错了:
```shell
pip3 install -U git+https://github.com/youfou/wxpy.git@develop
```

**Comment by mapleflow** [comment]
很感谢。
