### ISSUE TITLE
扫码登录不上

### ISSUE THREAD

**Issue by Divad1111** [youfou/wxpy#413]
>>> from wxpy import *
>>> bot = Bot()
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wxpy\api\bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\itchat\components\register.py", line 35, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\itchat\components\login.py", line 66, in login
    self.show_mobile_login()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\itchat\components\login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'
>>>

**Comment by WangPney** [comment]
都不维护了 怎么可能登得上。。。

**Comment by Divad1111** [comment]
哈哈

**Comment by Jarvan-via** [comment]
反应用不了的朋友 请先到微信网页版去试下扫码登录  如果那里可登录就能用否则就用不了。

**Comment by WangPney** [comment]
你要是商业化的 看这个吧https://wkteam.gitbook.io/api/

**Comment by GengchenXU** [comment]
你网页版微信登不了
