### ISSUE TITLE
相同微信号，老服务器上可正常登录，但是换新的服务器却提示KeyError: 'pass_ticket'

### ISSUE THREAD

**Issue by Cyrus-Jiang** [youfou/wxpy#414]
之前一直在阿里云上登录该微信号，但是最近要换另一个海外的服务器去运行，扫码点击登录之后提示：

```Please scan the QR code to log in.
INFO:itchat:Please scan the QR code to log in.
Please press confirm on your phone.
INFO:itchat:Please press confirm on your phone.
Loading the contact, this may take a little while.
INFO:itchat:Loading the contact, this may take a little while.

Traceback (most recent call last):
  File "nkBot5.py", line 77, in <module>
    bot = Bot(console_qr=True)
  File "/usr/local/python3/lib/python3.6/site-packages/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/usr/local/python3/lib/python3.6/site-packages/itchat/components/register.py", line 35, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/python3/lib/python3.6/site-packages/itchat/components/login.py", line 66, in login
    self.show_mobile_login()
  File "/usr/local/python3/lib/python3.6/site-packages/itchat/components/login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'
```

- 两台服务器的Python版本和wxpy以及itchat版本以及代码均一致

- 新服务器上也尝试使用该脚本登陆其他的号码（包括尝试自己一直使用的个人微信号），报错信息相同

- 该账号于老服务器可登录，但新服务器无法登陆

- 新服务器上有另外一个微信账号一直在正常使用，依然使用wxpy，代码逻辑不同

- 当前新服务器的代码目录有把之前的`__pycache__`、`wxpy.pkl`、`wxpy_puid.pkl`等文件copy过来

**Comment by Cyrus-Jiang** [comment]
已解决，启用缓存` cache_path=True` 这样可以使用迁移前的缓存文件登陆，目前看来我这边可能没登录过的账号应该都会被限制登录
