### ISSUE TITLE
Message.reply_raw_msg(...)报错

### ISSUE THREAD

**Issue by rxu202** [youfou/wxpy#44]
试用文档中的例子：
`@bot.register(msg_types=CARD)
            def reply_text(msg):
                msg.chat.send_raw_msg(msg.raw['MsgType'], msg.raw['Content'])`
报错信息如下：
>>> 2017-05-02 23:23:07,260 root         CRITICAL UNCAUGHT EXCEPTION:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/Users/rxu/dev/wxpy-master/wxpy/api/chats/chat.py", line 29, in wrapped
    kwargs_, attrs_ = func(self, *args, **kwargs)
  File "/Users/rxu/dev/wxpy-master/wxpy/api/chats/chat.py", line 229, in send_raw_msg
    req = BaseRequest(self.bot, uri=uri)
  File "/Users/rxu/dev/wxpy-master/wxpy/utils/base_request.py", line 25, in __init__
    self.url = self.bot.core.loginInfo['url'] + uri
TypeError: Can't convert 'NoneType' object to str implicitly

**Comment by youfou** [comment]
这个问题在最新的 `develop` 分支中被修复了，谢谢你的反馈！

安装 `develop` 分支:

```shell
pip3 install -U git+https://github.com/youfou/wxpy.git@develop
```
