### ISSUE TITLE
msg.chat.accept()方法报错

### ISSUE THREAD

**Issue by frank201524** [youfou/wxpy#51]
你好 代码如下
@bot.register()
def print_others(msg):
logging.info(msg)

if msg.type == "Note" and "刚刚把你添加到通讯录" in msg.text:
    logging.info("add new friend: " + msg.chat.nick_name)
    msg.chat.send_image('new_user.jpg')
    msg.chat.accept()
    return

我的微信机器人账号设置的加我好友时不需要验证，所以用户添加我到通讯录之后可以直接发消息给我，然后调用msg.chat.accept()时就有报错，报错信息如下

Fri, 28 Apr 2017 11:56:45 bot.py[line:330] ERROR
An error occurred in <function print_others at 0x7f6ea15c4730>.
Traceback (most recent call last):
File "/opt/python35/lib/python3.5/site-packages/wxpy/api/bot.py", line 326, in process
ret = config.func(msg)
File "ttsbot-prod.py", line 36, in print_others
bot.accept_friend(msg.chat)
File "/opt/python35/lib/python3.5/site-packages/wxpy/api/bot.py", line 253, in accept_friend
do()
File "/opt/python35/lib/python3.5/site-packages/wxpy/utils/misc.py", line 59, in wrapped
smart_map(check_response_body, ret)
File "/opt/python35/lib/python3.5/site-packages/wxpy/utils/misc.py", line 178, in smart_map
return func(i, *args, **kwargs)
File "/opt/python35/lib/python3.5/site-packages/wxpy/utils/misc.py", line 25, in check_response_body
raise ResponseError('ret: {}; err_msg: {}'.format(ret, err_msg))
wxpy.exceptions.ResponseError: ret: -1; err_msg:

**Comment by OSMeteor** [comment]
不应该是先接受请求然后发消息 ？

**Comment by youfou** [comment]
上述你帖出的代码中, accept 的对象并非添加机器人的陌生人，而是“好友请求消息” 的发送者。

正确的写法请参考文档中的示例代码
http://wxpy.readthedocs.io/zh/latest/bot.html#wxpy.Bot.accept_friend
