### ISSUE TITLE
在多个群同步消息报错

### ISSUE THREAD

**Issue by tarfly** [youfou/wxpy#55]
在多个群同步消息报错

`@bot.register(groups, except_self=False)
def wxpy_group(msg):
    # msg.reply('你好');
    # msg.reply_image('QR.png');
    sync_message_in_groups(msg, groups)
    # return '你好'
embed()`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/wxpy/ext/sync_message_in_groups.py", line 98, in process
    raise_for_unsupported=raise_for_unsupported
  File "/usr/local/lib/python3.5/site-packages/wxpy/api/messages/message.py", line 448, in forward
    return wrapped_send('msg')
  File "/usr/local/lib/python3.5/site-packages/wxpy/api/messages/message.py", line 418, in wrapped_send
    '\n' + str(suffix) if suffix else '',
  File "/usr/local/lib/python3.5/site-packages/wxpy/api/chats/chat.py", line 43, in wrapped
    ret_ = do()
  File "/usr/local/lib/python3.5/site-packages/wxpy/utils/misc.py", line 50, in wrapped
    smart_map(check_response_body, ret)
  File "/usr/local/lib/python3.5/site-packages/wxpy/utils/misc.py", line 185, in smart_map
    return func(i, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/wxpy/utils/misc.py", line 31, in check_response_body
    raise ResponseError(dict(err_code=err_code, err_msg=err_msg))`

**Comment by youfou** [comment]
Trackback 信息不完整，最后的错误码是多少？
