### ISSUE TITLE
wxpy.exceptions.ResponseError: err_code: -1001; err_msg: \u65e0\u6cd5\u627e\u5230\u5bf9\u5e94\u7684\u6210\u5458

### ISSUE THREAD

**Issue by cherish1896** [youfou/wxpy#57]
wxpy.exceptions.ResponseError: err_code: -1001; err_msg:无法找到对应的成员

> Exception in thread _listen:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\api\bot.py", line 467, in _listen
    self._process_message(msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\api\bot.py", line 410, in _process_message
    config = self.registered.get_config(msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\api\messages\registered.py", line 26, in get_config
    if not conf.enabled or (conf.except_self and msg.sender == self.bot.self):
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\api\messages\message.py", line 287, in sender
    return self._get_chat_by_user_name(self.raw.get('FromUserName'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\api\messages\message.py", line 337, in _get_chat_by_user_name
    _chat = match_in_chats(self.bot.groups())
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\utils\misc.py", line 74, in wrapped
    ret = Groups(ret)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\api\chats\groups.py", line 17, in __init__
    filter(lambda x: x.bot.self in x, group_list)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\api\chats\groups.py", line 17, in <lambda>
    filter(lambda x: x.bot.self in x, group_list)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\api\chats\group.py", line 39, in __contains__
    for member in self.members:
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\api\chats\group.py", line 33, in members
    raw_member_list() or raw_member_list(True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\api\chats\group.py", line 27, in raw_member_list
    self.update_group()
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\api\chats\group.py", line 109, in update_group
    super(Group, self).__init__(do(), self.bot)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\utils\misc.py", line 50, in wrapped
    smart_map(check_response_body, ret)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\utils\misc.py", line 185, in smart_map
    return func(i, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wxpy\utils\misc.py", line 31, in check_response_body
    raise ResponseError(err_code=err_code, err_msg=err_msg)
wxpy.exceptions.ResponseError: err_code: -1001; err_msg: \u65e0\u6cd5\u627e\u5230\u5bf9\u5e94\u7684\u6210\u5458

麻烦大神们给看看是咋回事

**Comment by cherish1896** [comment]
> __title__ = 'wxpy'
__version__ = '0.3.9.6'
__author__ = 'Youfou'
__license__ = 'MIT'
__copyright__ = '2017, Youfou'

**Comment by ch3n2k** [comment]
回退到0.3.9.5就好了

**Comment by youfou** [comment]
@cherish1896 @ch3n2k @runbing 
抱歉，-1001 错误与我在 0.3.9.6 版本中的一个改动有关，现已在开发分支中修复。

安装开发分支:
```shell
pip3 install -U git+https://github.com/youfou/wxpy.git@develop
```

**Comment by youfou** [comment]
这个问题也和Web微信的一个BUG有关，具体表现为：
> 当从接口获取群列表时，会返回一些不存在的或者已经离开的群，但这些群的群成员为陌生人，或干脆为空的。

我们可以把这些不应存在的群称为: shadow group

因此我在 0.3.9.6 版本中增加了验证“群有效性”的逻辑，来过滤 shadow group:
> 在获取到群列表后，判断各个群中是否包含机器人自身，包含才认为有效

然而，我没有考虑到的是，在 wxpy 中还有两个受影响的逻辑:
1. 当尝试访问一个空群成员列表时(一些成员数量非常多的群会默认返回空成员列表)，会先请求更新这个群成员列表
2. 每当有新的群消息到达时，会尝试通过微信提供的 `FromUserName` 在机器人已知的群列表中进行比较，来判断来自哪个群

因此，当机器人中存在成员列表为空的 shadow group 时，wxpy 会在每次收到群消息时，去请求更新这些 shadow group。
因此高频的群成员列表更新请求，会导致微信返回 1205 错误，当然也会因此不返回我们本来需要的请成员列表。
而 itchat 中不会因为 1205 错误抛出异常，而是因为获取不到所需的成员列表而返回 -1001 错误: 找不到所需的群成员。

**Comment by sandy8508** [comment]
0.3.9.8最新版本己经包含这个fix了么? @youfou
