### ISSUE TITLE
发送图片失败

### ISSUE THREAD

**Issue by rxu202** [youfou/wxpy#58]
Hello，最近遇到的一个问题是，log里出现这种错误，图片发不出去：大概搜了一下，error code 1205好像是说微信有发送图片频率的限制，请问作者能帮忙确认一下吗？这个限制具体是怎样的呢？发现很难找到系统的关于微信的相应的限制的文档，还有API Error Code的文档，请问有什么文档推荐吗？谢谢！
`2017-05-19 15:21:26,196 wxpy.api.bot ERROR
An error occurred in <function process_editors at 0x7efc5d4b2f28>.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/wxpy/api/bot.py", line 418, in process
    ret = config.func(msg)
  File "weee_helper_bot.py", line 459, in process_editors
    send_group_messages(msg, msgs)
  File "weee_helper_bot.py", line 481, in send_group_messages
    send_to_group(group, msgs, news_groups[key])
  File "weee_helper_bot.py", line 500, in send_to_group
    group.send_image(m.body)
  File "/usr/local/lib/python3.5/site-packages/wxpy/api/chats/chat.py", line 43, in wrapped
    ret_ = do()
  File "/usr/local/lib/python3.5/site-packages/wxpy/utils/misc.py", line 49, in wrapped
    smart_map(check_response_body, ret)
  File "/usr/local/lib/python3.5/site-packages/wxpy/utils/misc.py", line 184, in smart_map
    return func(i, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/wxpy/utils/misc.py", line 30, in check_response_body
    raise ResponseError(dict(err_code=err_code, err_msg=err_msg))
wxpy.exceptions.ResponseError: {'err_code': 1205, 'err_msg': ''}`

**Comment by youfou** [comment]
1205 错误通常表示请求频率过高，需要暂缓。
只有 Web 微信的内部开发人员才掌握完整的错误号说明，我们只能从外部猜测。
