### ISSUE TITLE
执行文档中代码出错

### ISSUE THREAD

**Issue by biubiubiucc** [youfou/wxpy#64]
好友名片这一段儿

from wxpy import *
bot = Bot()
@bot.register(msg_types=CARD)
def reply_text(msg):
    msg.chat.send_raw_msg(msg.raw['MsgType'], msg.raw['Content'])

然后出错了~~

In [1]: ERROR:wxpy.api.bot:
An error occurred in <function reply_text at 0x1032ef488>.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/wxpy/api/bot.py", line 421, in ps
    ret = config.func(msg)
  File "checkIndex.py", line 12, in reply_text
    msg.chat.send_raw_msg(msg.raw['MsgType'], msg.raw['Content'])
  File "/usr/local/lib/python3.5/site-packages/wxpy/api/chats/chat.py", line 29d
    kwargs_, attrs_ = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/wxpy/api/chats/chat.py", line 22g
    req = BaseRequest(self.bot, uri=uri)
  File "/usr/local/lib/python3.5/site-packages/wxpy/utils/base_request.py", lin_
    self.url = self.bot.core.loginInfo['url'] + uri
TypeError: Can't convert 'NoneType' object to str implicitly

**Comment by youfou** [comment]
先前版本中 send_raw_msg() 存在问题，已经在最新版本中修复
