### ISSUE TITLE
Error -1004

### ISSUE THREAD

**Issue by rxu202** [youfou/wxpy#67]
Traceback (most recent call last):
  File "weee_helper_bot.py", line 362, in send_to_group
    group.send_image(m._body)
  File "/usr/local/lib/python3.5/site-packages/wxpy/api/chats/chat.py", line 43, in wrapped
    ret_ = do()
  File "/usr/local/lib/python3.5/site-packages/wxpy/utils/misc.py", line 49, in wrapped
    smart_map(check_response_body, ret)
  File "/usr/local/lib/python3.5/site-packages/wxpy/utils/misc.py", line 184, in smart_map
    return func(i, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/wxpy/utils/misc.py", line 30, in check_response_body
    raise ResponseError(dict(err_code=err_code, err_msg=err_msg))
wxpy.exceptions.ResponseError: {'err_msg': '\\u670d\\u52a1\\u5668\\u8fd4\\u56de\\u5f02\\u5e38\\u503c', 'err_code': -1004}

请问你知道-1004是代表什么吗？Unicode的err_msg转成中文是：服务器返回异常值。

**Comment by youfou** [comment]
-1004 错误是 itchat 层返回的，看了下 itchat 的源码， -1004 是因为微信服务端返回无法用 JSON 解析的内容。

这个问题必现吗？
